FinalDat$pressure1224<-FinalDat$pressure_12h_Den-pressure_24h_Den
FinalDat$humidity1224<-FinalDat$humidity_12h_Den-FinalDat$humidity_24h_Den
FinalDat$temp1224<-FinalDat$temp_12h_Den-FinalDat$temp_24h_Den
FinalDat$wind_speed1224<-FinalDat$wind_speed_12h_Den-FinalDat$wind_speed_24h_Den
FinalDat$clouds_all1224<-FinalDat$clouds_all_12h_Den-clouds_all_24h_Den

FinalDat$pressure624<-FinalDat$pressure_6h_Den-pressure_24h_Den
FinalDat$humidity624<-FinalDat$humidity_6h_Den-FinalDat$humidity_24h_Den
FinalDat$temp624<-FinalDat$temp_6h_Den-FinalDat$temp_24h_Den
FinalDat$wind_speed624<-FinalDat$wind_speed_6h_Den-FinalDat$wind_speed_24h_Den
FinalDat$clouds_all624<-FinalDat$clouds_all_6h_Den-clouds_all_24h_Den

FinalDat$pressure324<-FinalDat$pressure_3h_Den-pressure_24h_Den
FinalDat$humidity324<-FinalDat$humidity_3h_Den-FinalDat$humidity_24h_Den
FinalDat$temp324<-FinalDat$temp_3h_Den-FinalDat$temp_24h_Den
FinalDat$wind_speed324<-FinalDat$wind_speed_3h_Den-FinalDat$wind_speed_24h_Den
FinalDat$clouds_all324<-FinalDat$clouds_all_3h_Den-clouds_all_24h_Den

FinalDat$pressure124<-FinalDat$pressure_1h_Den-pressure_24h_Den
FinalDat$humidity124<-FinalDat$humidity_1h_Den-FinalDat$humidity_24h_Den
FinalDat$temp124<-FinalDat$temp_1h_Den-FinalDat$temp_24h_Den
FinalDat$wind_speed124<-FinalDat$wind_speed_1h_Den-FinalDat$wind_speed_24h_Den
FinalDat$clouds_all124<-FinalDat$clouds_all_1h_Den-clouds_all_24h_Den

FinalDat$pressure612<-FinalDat$pressure_6h_Den-pressure_12h_Den
FinalDat$humidity612<-FinalDat$humidity_6h_Den-FinalDat$humidity_12h_Den
FinalDat$temp612<-FinalDat$temp_6h_Den-FinalDat$temp_12h_Den
FinalDat$wind_speed612<-FinalDat$wind_speed_6h_Den-FinalDat$wind_speed_12h_Den
FinalDat$clouds_all612<-FinalDat$clouds_all_6h_Den-clouds_all_12h_Den

FinalDat$pressure312<-FinalDat$pressure_3h_Den-pressure_12h_Den
FinalDat$humidity312<-FinalDat$humidity_3h_Den-FinalDat$humidity_12h_Den
FinalDat$temp312<-FinalDat$temp_3h_Den-FinalDat$temp_12h_Den
FinalDat$wind_speed312<-FinalDat$wind_speed_3h_Den-FinalDat$wind_speed_12h_Den
FinalDat$clouds_all312<-FinalDat$clouds_all_3h_Den-clouds_all_12h_Den

FinalDat$pressure112<-FinalDat$pressure_1h_Den-pressure_12h_Den
FinalDat$humidity112<-FinalDat$humidity_1h_Den-FinalDat$humidity_12h_Den
FinalDat$temp112<-FinalDat$temp_1h_Den-FinalDat$temp_12h_Den
FinalDat$wind_speed112<-FinalDat$wind_speed_1h_Den-FinalDat$wind_speed_12h_Den
FinalDat$clouds_all112<-FinalDat$clouds_all_1h_Den-clouds_all_12h_Den

FinalDat$pressure36<-FinalDat$pressure_3h_Den-pressure_6h_Den
FinalDat$humidity36<-FinalDat$humidity_3h_Den-FinalDat$humidity_6h_Den
FinalDat$temp36<-FinalDat$temp_3h_Den-FinalDat$temp_6h_Den
FinalDat$wind_speed36<-FinalDat$wind_speed_3h_Den-FinalDat$wind_speed_6h_Den
FinalDat$clouds_all36<-FinalDat$clouds_all_3h_Den-clouds_all_6h_Den

FinalDat$pressure16<-FinalDat$pressure_1h_Den-pressure_6h_Den
FinalDat$humidity16<-FinalDat$humidity_1h_Den-FinalDat$humidity_6h_Den
FinalDat$temp16<-FinalDat$temp_1h_Den-FinalDat$temp_6h_Den
FinalDat$wind_speed16<-FinalDat$wind_speed_1h_Den-FinalDat$wind_speed_6h_Den
FinalDat$clouds_all16<-FinalDat$clouds_all_1h_Den-clouds_all_6h_Den

FinalDat$pressure13<-FinalDat$pressure_1h_Den-pressure_3h_Den
FinalDat$humidity13<-FinalDat$humidity_1h_Den-FinalDat$humidity_3h_Den
FinalDat$temp13<-FinalDat$temp_1h_Den-FinalDat$temp_3h_Den
FinalDat$wind_speed13<-FinalDat$wind_speed_1h_Den-FinalDat$wind_speed_3h_Den
FinalDat$clouds_all13<-FinalDat$clouds_all_1h_Den-clouds_all_3h_Den
