```{r}
require(caTools)
dat<-FinalDat2
set.seed(101) 
dat_sample<-dat[sample(nrow(dat), 3000), ]
sample = sample.split(dat_sample$pressure, SplitRatio = .75)
trainset = subset(dat_sample, sample == TRUE)
testset  = subset(dat_sample, sample == FALSE)

mean_train<-apply(trainset, 2, mean)
var_train<-apply(trainset, 2, var)

train <- t((t(trainset)-mean_train)/sqrt(var_train))
apply(train, 2, mean)
apply(train, 2, var)

trainset<-data.frame(train, lpsa=dat[dat$train == T,]$lpsa)

##	NEED TO APPLY TRAINING MEAN AND STDEV TO STANDARDIZE TEST SET!!  ##
test<-as.data.frame(t((t(dat[dat$train == F, 1:8])-mean_train)/sqrt(var_train)))
dat.test <- data.frame(test, lpsa=dat[dat$train == F,]$lpsa)
apply(test, 2, mean)
apply(test, 2, var)

Q_train = as.factor(trainset$Question)
Q_test = as.factor(testset$Question)
```
```{r}
######## 24 Hour Model ############
 ans24hrs <- glm(as.factor(Question) ~
 temp_24h_Den
 +pressure_24h_Den+humidity_24h_Den+wind_speed_24h_Den+wind_dir_24h_Den
 +rain_1h_24h_Den+rain_3h_24h_Den+snow_1h_24h_Den
+snow_3h_24h_Den+clouds_all_24h_Den
 +weather_main_24h_Den_Dummy, family=binomial(), data=trainset)

# summary(ans24hrs)
# coef(ans24hrs)
# summary(ans24hrs)$coef
# summary(ans24hrs)$coef[,4]
# glm.probs=predict(ans24hrs,type="response")
# glm.probs[1:40]

summary(ans24hrs)

glm.probs_train = predict(ans24hrs, type = "response")
glm.probs_test = predict(ans24hrs, testset, type = "response")
glm_24.pred_train = rep(0, length(trainset$Question))
glm_24.pred_test = rep(0, length(testset$Question))
glm_24.pred_train[glm.probs_train > 0.5] = 1
glm_24.pred_test[glm.probs_test > 0.5] = 1
table(glm_24.pred_train, Q_train)
mean(glm_24.pred_train == Q_train)
table(glm_24.pred_test, Q_test)
mean(glm_24.pred_test == Q_test)
```
```{r}
######## 12 Hour Model ############
ans12hrs <- glm(as.factor(Question) ~
temp_12h_Den
+pressure_12h_Den+humidity_12h_Den+wind_speed_12h_Den+wind_dir_12h_Den
+rain_1h_12h_Den+rain_3h_12h_Den+snow_1h_12h_Den
+snow_3h_12h_Den+clouds_all_12h_Den
+weather_main_12h_Den_Dummy
+I((pressure_12h_Den-pressure_24h_Den)/(24-12))
+I((temp_12h_Den-temp_24h_Den)/(24-12))
+I((humidity_12h_Den-humidity_24h_Den)/(24-12))
+I((wind_speed_12h_Den-wind_speed_24h_Den)/(24-12))
+I((clouds_all_12h_Den-clouds_all_24h_Den)/(24-12))
, family=binomial(), data=trainset)
	
summary(ans12hrs)
glm.probs_train = predict(ans12hrs, type = "response")
glm.probs_test = predict(ans12hrs, testset, type = "response")
glm_12.pred_train = rep(0, length(trainset$Question))
glm_12.pred_test = rep(0, length(testset$Question))
glm_12.pred_train[glm.probs_train > 0.5] = 1
glm_12.pred_test[glm.probs_test > 0.5] = 1
table(glm_12.pred_train, Q_train)
mean(glm_12.pred_train == Q_train)
table(glm_12.pred_test, Q_test)
mean(glm_12.pred_test == Q_test)

```
```{r}
######## 6 Hour Model ############
ans6hrs <- glm(as.factor(Question) ~
temp_6h_Den
+pressure_6h_Den+humidity_6h_Den+wind_speed_6h_Den+wind_dir_6h_Den
+rain_1h_6h_Den+rain_3h_6h_Den+snow_1h_6h_Den
+snow_3h_6h_Den+clouds_all_6h_Den
+weather_main_6h_Den_Dummy

+I((pressure_6h_Den-pressure_24h_Den)/(24-6))
+I((temp_6h_Den-temp_24h_Den)/(24-6))
+I((humidity_6h_Den-humidity_24h_Den)/(24-6))
+I((wind_speed_6h_Den-wind_speed_24h_Den)/(24-6))
+I((clouds_all_6h_Den-clouds_all_24h_Den)/(24-6))

+I((pressure_6h_Den-pressure_12h_Den)/(12-6))
+I((temp_6h_Den-temp_12h_Den)/(12-6))
+I((humidity_6h_Den-humidity_12h_Den)/(12-6))
+I((wind_speed_6h_Den-wind_speed_12h_Den)/(12-6))
+I((clouds_all_6h_Den-clouds_all_12h_Den)/(12-6))

, family=binomial(), data=trainset)

glm.probs_train = predict(ans6hr, type = "response")
glm.probs_test = predict(ans6hr, testset, type = "response")
glm_6.pred_train = rep(0, length(trainset$Question))
glm_6.pred_test = rep(0, length(testset$Question))
glm_6.pred_train[glm.probs_train > 0.5] = 1
glm_6.pred_test[glm.probs_test > 0.5] = 1
table(glm_6.pred_train, Q_train)
mean(glm_6.pred_train == Q_train)
table(glm_6.pred_test, Q_test)
mean(glm_6.pred_test == Q_test)

	
```
```{r}
######## 3 Hour Model ############
ans3hrs <- glm(as.factor(Question) ~
temp_3h_Den
+pressure_3h_Den+humidity_3h_Den+wind_speed_3h_Den+wind_dir_3h_Den
+rain_1h_3h_Den+rain_3h_3h_Den+snow_1h_3h_Den
+snow_3h_3h_Den+clouds_all_3h_Den
+weather_main_3h_Den_Dummy
+I((pressure_3h_Den-pressure_24h_Den)/(24-3))
+I((temp_3h_Den-temp_24h_Den)/(24-3))
+I((humidity_3h_Den-humidity_24h_Den)/(24-3))
+I((wind_speed_3h_Den-wind_speed_24h_Den)/(24-3))
+I((clouds_all_3h_Den-clouds_all_24h_Den)/(24-3))

+I((pressure_3h_Den-pressure_12h_Den)/(12-3))
+I((temp_3h_Den-temp_12h_Den)/(12-3))
+I((humidity_3h_Den-humidity_12h_Den)/(12-3))
+I((wind_speed_3h_Den-wind_speed_12h_Den)/(12-3))
+I((clouds_all_3h_Den-clouds_all_12h_Den)/(12-3))

+I((pressure_3h_Den-pressure_6h_Den)/(6-3))
   +I((temp_3h_Den-temp_6h_Den)/(6-3))
+I((humidity_3h_Den-humidity_6h_Den)/(6-3))
   +I((wind_speed_3h_Den-wind_speed_6h_Den)/(6-3))
+I((clouds_all_3h_Den-clouds_all_6h_Den)/(6-3))
, family=binomial(), data=trainset)

glm.probs_train = predict(ans3hrs, type = "response")
glm.probs_test = predict(ans3hrs, testset, type = "response")
glm_3.pred_train = rep(0, length(trainset$Question))
glm_3.pred_test = rep(0, length(testset$Question))
glm_3.pred_train[glm.probs_train > 0.5] = 1
glm_3.pred_test[glm.probs_test > 0.5] = 1
table(glm_3.pred_train, Q_train)
mean(glm_3.pred_train == Q_train)
table(glm_3.pred_test, Q_test)
mean(glm_3.pred_test == Q_test)

```
```{r}	
######## 1 Hour Model ############
ans1hrs <- glm(as.factor(Question) ~
temp_1h_Den
+pressure_1h_Den+humidity_1h_Den+wind_speed_1h_Den+wind_dir_1h_Den
+rain_1h_1h_Den+rain_3h_1h_Den+snow_1h_1h_Den
+snow_3h_1h_Den+clouds_all_1h_Den
+weather_main_1h_Den_Dummy

+I((pressure_1h_Den-pressure_24h_Den)/(24-1))
+I((temp_1h_Den-temp_24h_Den)/(24-1))
+I((humidity_1h_Den-humidity_24h_Den)/(24-1))
+I((wind_speed_1h_Den-wind_speed_24h_Den)/(24-1))
+I((clouds_all_1h_Den-clouds_all_24h_Den)/(24-1))

+I((pressure_1h_Den-pressure_12h_Den)/(12-1))
+I((temp_1h_Den-temp_12h_Den)/(12-1))
+I((humidity_1h_Den-humidity_12h_Den)/(12-1))
+I((wind_speed_1h_Den-wind_speed_12h_Den)/(12-1))
+I((clouds_all_1h_Den-clouds_all_12h_Den)/(12-1))

+I((pressure_1h_Den-pressure_6h_Den)/(6-1))
+I((temp_1h_Den-temp_6h_Den)/(6-1))
+I((humidity_1h_Den-humidity_6h_Den)/(6-1))
+I((wind_speed_1h_Den-wind_speed_6h_Den)/(6-1))
+I((clouds_all_1h_Den-clouds_all_6h_Den)/(6-1))

+I((pressure_1h_Den-pressure_3h_Den)/(3-1))
+I((temp_1h_Den-temp_3h_Den)/(3-1))
+I((humidity_1h_Den-humidity_3h_Den)/(3-1))
+I((wind_speed_1h_Den-wind_speed_3h_Den)/(3-1))
+I((clouds_all_1h_Den-clouds_all_3h_Den)/(3-1))

, family=binomial(), data=trainset)
	
glm.probs_train = predict(ans1hrs, type = "response")
glm.probs_test = predict(ans1hrs, testset, type = "response")
glm_1.pred_train = rep(0, length(trainset$Question))
glm_1.pred_test = rep(0, length(testset$Question))
glm_1.pred_train[glm.probs_train > 0.5] = 1
glm_1.pred_test[glm.probs_test > 0.5] = 1
table(glm_1.pred_train, Q_train)
mean(glm_1.pred_train == Q_train)
table(glm_1.pred_test, Q_test)
mean(glm_1.pred_test == Q_test)

```

